"""Set equality is not currency, and an absent row is not a zero.

``UniverseCertification`` establishes that the contract list, the quote snapshot
and the Greeks snapshot name the same identities. On Aug 26 all three named
roughly five hundred contracts that had expired on Aug 25, carrying Aug-25
market timestamps, and on Aug 27 those were gone while roughly five hundred
Aug-26 contracts had replaced them. So the strongest universe state this
repository can award -- ``DEDICATED_CONTRACT_LIST_MATCHED_SNAPSHOT_UNIVERSE`` --
is compatible with a universe that is not this session's, and something has to
say so.

``src/adapters/thetadata/analytical_universe.py`` is that something. It
partitions one certified capture's listed universe into what an analytical
dataset could use and what it could not, with a named reason per exclusion and a
set hash per class.

**Nothing here is evidence about ThetaData.** The capture is generated by
``tests.synthetic_capture``, whose ``stale_expirations`` parameter exists
because the generator could not previously produce the behaviour this release
accounts for: every row went through the pricer, and a Black-Scholes input with
negative time is degenerate. The conclusions about the vendor live in
``docs/DATA_ELIGIBILITY.md`` and in the two live-capture fixtures.

These tests also hold the release's most important negative claim shut: the
certification report, its schema and its ``report_hash`` are **unchanged**. The
partition is a second report over the same verified bytes, so the two frozen
live-capture artifacts still reproduce.
"""

from __future__ import annotations

import json
import pathlib
from datetime import date

import pytest

from src.adapters.thetadata.analytical_universe import (
    ANALYTICAL_UNIVERSE_ALGORITHM_VERSION,
    ANALYTICAL_UNIVERSE_REPORT_SCHEMA_VERSION,
    AnalyticalUniverseError,
    UniverseClass,
    analytical_universe,
    analytical_universe_of,
)
from src.adapters.thetadata.capture_certification import (
    capture_universe,
    certify_capture,
    load_capture,
)
from src.domain.analytical_universe import (
    ANALYTICAL_UNIVERSE_SCHEMA_VERSION,
    AnalyticalExclusion,
)
from tests.synthetic_capture import SyntheticVendor, write_capture

#: A session before the capture's. 2026-08-07 is the Friday before the
#: 2026-08-10 valuation the generator defaults to.
RETAINED_SESSION = date(2026, 8, 7)


def _retaining_vendor(**overrides) -> SyntheticVendor:
    """A vendor whose snapshots still return an expired expiration.

    Eight identities -- four strikes, two rights -- three of which also carry an
    open-interest row, so the precedence between the two exclusion reasons is
    observable rather than assumed.
    """
    base = {
        "stale_expirations": (RETAINED_SESSION,),
        "stale_with_open_interest": 3,
    }
    base.update(overrides)
    return SyntheticVendor(**base)


@pytest.fixture(scope="module")
def retaining(tmp_path_factory) -> pathlib.Path:
    root = tmp_path_factory.mktemp("retaining")
    return write_capture(root / "cap", _retaining_vendor())


@pytest.fixture(scope="module")
def current(tmp_path_factory) -> pathlib.Path:
    """The same generator with nothing retained. The control."""
    root = tmp_path_factory.mktemp("current")
    return write_capture(root / "cap", SyntheticVendor())


@pytest.fixture(scope="module")
def retaining_report(retaining: pathlib.Path):
    return analytical_universe(retaining)


# --- The finding: three agreeing endpoints, one wrong universe ---------------


def test_the_three_endpoints_agree_and_the_universe_is_still_not_this_session(
    retaining,
):
    """The regression, stated as the two facts that have to coexist.

    Certification awards its strongest universe state, because the three
    responses really do name the same identities. The partition says eight of
    them expired before the session opened. Both are true, and before v2.1.28
    only the first was said.
    """
    report = certify_capture(retaining)
    universe = report.as_dict()["universe"]
    assert universe["quote_matches_list"] is True
    assert universe["greeks_matches_list"] is True
    assert universe["state"] == "DEDICATED_CONTRACT_LIST_MATCHED_SNAPSHOT_UNIVERSE"

    partition = analytical_universe_of(capture_universe(load_capture(retaining)))
    assert (
        partition.class_counts[UniverseClass.EXCLUDED_EXPIRED_BEFORE_SESSION.value] == 8
    )
    assert not partition.permits_trusted_analytical_universe


def test_the_session_comes_from_the_verified_request_not_from_a_clock(
    retaining_report,
):
    """Which session the universe is *of* decides which contracts are stale.

    It is read off the contract-list request -- the ``date`` parameter the
    vendor was actually asked, inside the preflight-approval digest stamped on
    every manifest record -- and cross-checked against the session the capture's
    own valuation timestamp resolves to. A capture whose two records of its
    session disagree is refused a trusted analytical universe rather than
    partitioned against whichever one was read first.
    """
    assert retaining_report.market_session_date == date(2026, 8, 10)
    assert (
        retaining_report.market_session_source == "VERIFIED_CONTRACT_LIST_REQUEST_DATE"
    )
    assert retaining_report.valuation_session_date == date(2026, 8, 10)
    assert retaining_report.sessions_agree


def test_a_capture_whose_two_session_records_disagree_is_not_trusted(retaining):
    """The cross-check has to be able to fail, or it is not a check."""
    import dataclasses

    universe = capture_universe(load_capture(retaining))
    shifted = dataclasses.replace(universe, session_date="2026-08-11")
    report = analytical_universe_of(shifted)
    assert not report.sessions_agree
    assert any("disagree" in blocker for blocker in report.blockers)
    assert not report.permits_trusted_analytical_universe


@pytest.mark.parametrize(
    "timestamp",
    ["", "not-a-timestamp", "2026-08-10T10:01:34"],
    ids=["absent", "unparseable", "naive"],
)
def test_an_unreadable_capture_clock_costs_the_capture_its_trust(retaining, timestamp):
    """A clock that cannot be read is not a clock that agrees.

    The naive case is the one worth spelling out: reading it would mean
    choosing a timezone, and the whole cross-check is about which session the
    capture is of. Defaulting the second record to the first would make the
    comparison compare a value with itself.
    """
    import dataclasses

    universe = dataclasses.replace(
        capture_universe(load_capture(retaining)), valuation_timestamp=timestamp
    )
    report = analytical_universe_of(universe)
    assert report.valuation_session_date is None
    # Absent, not disagreeing -- the two are different findings.
    assert report.sessions_agree
    assert any("could not be resolved" in blocker for blocker in report.blockers)
    assert not report.permits_trusted_analytical_universe


def test_a_universe_with_no_nameable_session_is_refused(retaining):
    """A partition against a session nobody can name is arithmetic, not a rule."""
    import dataclasses

    universe = dataclasses.replace(
        capture_universe(load_capture(retaining)), session_date=""
    )
    with pytest.raises(AnalyticalUniverseError, match="not a date"):
        analytical_universe_of(universe)


# --- Counting and exposure ---------------------------------------------------


def test_both_exclusion_reasons_are_counted_apart(retaining_report):
    """Requirement 7 at the capture layer.

    Two findings with different remedies: a retained contract clears itself at
    the next capture, an unreported open interest waits for a settlement figure.
    A single "excluded" count would make a universe nobody can reconcile.
    """
    counts = retaining_report.exclusion_counts
    assert set(counts) == {reason.value for reason in AnalyticalExclusion}
    assert counts[AnalyticalExclusion.EXPIRED_BEFORE_SESSION.value] == 8
    assert counts[AnalyticalExclusion.OPEN_INTEREST_NOT_REPORTED.value] > 0
    assert (
        retaining_report.excluded_count
        == counts[AnalyticalExclusion.EXPIRED_BEFORE_SESSION.value]
        + counts[AnalyticalExclusion.OPEN_INTEREST_NOT_REPORTED.value]
    )


def test_staleness_wins_over_a_missing_open_interest_row(retaining_report):
    """Five of the eight retained identities also have no open-interest row.

    All eight are reported as retained. Attributing a vendor-retention artefact
    to a settlement gap would double-count one finding and hide the other.
    """
    retained = retaining_report.identities_in(
        UniverseClass.EXCLUDED_EXPIRED_BEFORE_SESSION
    )
    assert len(retained) == 8
    assert {key.expiration for key in retained} == {RETAINED_SESSION}
    answered = sum(1 for key in retained if key in retaining_report.universe.answered)
    assert answered == 3
    unanswered = len(retained) - answered
    assert unanswered == 5
    # ... and none of those five is counted under the open-interest reason.
    unreported = retaining_report.identities_in(
        UniverseClass.EXCLUDED_OPEN_INTEREST_NOT_REPORTED
    )
    assert all(key.expiration > RETAINED_SESSION for key in unreported)


def test_every_listed_identity_is_classified_exactly_once(retaining_report):
    """Checkable by addition rather than trusted."""
    assert retaining_report.accounting_is_exhaustive
    assert sum(retaining_report.class_counts.values()) == retaining_report.listed_count
    assert (
        retaining_report.eligible_count + retaining_report.excluded_count
        == retaining_report.listed_count
    )


def test_excluded_identities_are_named_by_set_hash_not_only_counted(
    retaining_report,
):
    """Counts alone would let two different sets of eight look identical."""
    hashes = retaining_report.class_hashes
    assert set(hashes) == {c.value for c in UniverseClass}
    assert all(len(digest) == 64 for digest in hashes.values())
    assert (
        hashes[UniverseClass.EXCLUDED_EXPIRED_BEFORE_SESSION.value]
        != hashes[UniverseClass.EXCLUDED_OPEN_INTEREST_NOT_REPORTED.value]
    )


def test_the_report_says_it_imputes_nothing(retaining_report):
    """An eligibility rule is not a claim about what the vendor means."""
    data = retaining_report.as_dict()
    assert data["imputation_policy"].startswith("NONE.")
    assert "OI_IMPUTATION_POLICY_UNRESOLVED" in data["analytical_evidence_status"]
    assert "not weighted at zero" in data["imputation_policy"]


def test_a_clean_capture_is_still_not_a_trusted_analytical_universe(
    tmp_path_factory,
):
    """Clearing these two findings clears these two findings, and nothing else.

    A capture with a complete open interest and no retained expiration still has
    no vendor-established settlement date (OD-26) and no independent universe
    evidence (OD-11). The name says *universe* rather than *calculation* for
    exactly that reason, and certification's own verdict is unmoved.
    """
    root = tmp_path_factory.mktemp("clean") / "cap"
    write_capture(root, SyntheticVendor(complete_open_interest=True))
    report = analytical_universe(root)
    assert report.exclusion_counts == {
        AnalyticalExclusion.EXPIRED_BEFORE_SESSION.value: 0,
        AnalyticalExclusion.OPEN_INTEREST_NOT_REPORTED.value: 0,
    }
    assert report.permits_trusted_analytical_universe
    assert certify_capture(root).trusted_for_gex is False
    assert certify_capture(root).analytical_readiness == (
        "ADAPTER_CERTIFICATION_EVIDENCE"
    )


# --- 0DTE is not what this removes -------------------------------------------


def test_a_same_session_expiration_is_eligible(tmp_path_factory):
    """The guard that keeps the temporal rule from becoming a 0DTE filter.

    The generator's front expiration is moved onto the valuation date, so the
    capture carries a series that expires in the session it was taken in. It is
    eligible, and it is counted in its own class so the claim is checkable.
    """
    root = tmp_path_factory.mktemp("zero-dte") / "cap"
    vendor = SyntheticVendor(
        expirations=(date(2026, 8, 10), date(2026, 8, 24), date(2026, 9, 16)),
        complete_open_interest=True,
    )
    write_capture(root, vendor)
    report = analytical_universe(root)
    counts = report.class_counts
    assert counts[UniverseClass.ELIGIBLE_EXPIRING_THIS_SESSION.value] > 0
    assert counts[UniverseClass.EXCLUDED_EXPIRED_BEFORE_SESSION.value] == 0
    same_session = report.identities_in(UniverseClass.ELIGIBLE_EXPIRING_THIS_SESSION)
    assert {key.expiration for key in same_session} == {date(2026, 8, 10)}
    assert report.permits_trusted_analytical_universe


# --- Replay ------------------------------------------------------------------


def test_the_partition_is_a_function_of_the_stored_bytes(retaining):
    """Requirement 8. Two reads of the same capture classify identically."""
    first = analytical_universe(retaining)
    second = analytical_universe(retaining)
    assert first.classified == second.classified
    assert first.as_dict() == second.as_dict()
    assert first.report_hash() == second.report_hash()
    assert len(first.report_hash()) == 64


def test_a_different_capture_cannot_reproduce_the_hash(retaining, current):
    """A content hash that two different universes share is not one."""
    assert (
        analytical_universe(retaining).report_hash()
        != analytical_universe(current).report_hash()
    )


def test_the_report_is_json_serialisable_and_carries_its_versions(retaining_report):
    data = retaining_report.as_dict()
    assert data["schema_version"] == ANALYTICAL_UNIVERSE_REPORT_SCHEMA_VERSION
    assert data["algorithm_version"] == ANALYTICAL_UNIVERSE_ALGORITHM_VERSION
    assert data["eligibility_schema_version"] == ANALYTICAL_UNIVERSE_SCHEMA_VERSION
    round_tripped = json.loads(json.dumps(data, sort_keys=True))
    assert round_tripped == data


def test_the_canonical_payload_carries_no_local_path(retaining_report):
    """Two machines certifying one capture must agree about it.

    The same rule the certification report's canonical payload lives under: a
    filesystem path is a fact about a machine, and hashing one makes the report
    identify the machine rather than the finding.
    """
    encoded = json.dumps(retaining_report.canonical_payload(), sort_keys=True)
    for shape in (":\\", "/home/", "/Users/", "/" + "tmp/"):
        assert shape not in encoded


# --- What this release does not change ---------------------------------------


def test_certification_is_untouched_by_the_partition(retaining, current):
    """Requirement 9. The existing capture verification is unchanged.

    Two independent certifications of the same capture still agree, the schema
    version is the one v2.1.27 published, and ``trusted_for_gex`` is still the
    constant ``False`` it has been since v2.1.24. The partition adds a report;
    it does not edit one.
    """
    from src.adapters.thetadata.capture_certification import (
        CAPTURE_CERTIFICATION_SCHEMA_VERSION,
    )

    assert CAPTURE_CERTIFICATION_SCHEMA_VERSION == "capture-certification/2.1.27"
    for root in (retaining, current):
        first, second = certify_capture(root), certify_capture(root)
        assert first.report_hash() == second.report_hash()
        assert first.schema_version == CAPTURE_CERTIFICATION_SCHEMA_VERSION
        assert first.trusted_for_gex is False
        assert "analytical_universe" not in first.as_dict()


def test_the_open_interest_coverage_blocker_is_not_made_smaller(retaining):
    """The release accounts for retained identities. It does not net them off.

    ``OpenInterestCoverage`` counts every listed identity the open-interest
    endpoint did not answer, retained ones included, and its blocker text is
    unchanged. Quietly shrinking it would be this release clearing a
    certification gate it did not earn.
    """
    report = certify_capture(retaining)
    coverage = report.as_dict()["open_interest_coverage"]
    universe = capture_universe(load_capture(retaining))
    assert coverage["universe_count"] == len(universe.expected)
    assert coverage["oi_missing"] == len(universe.missing)
    assert coverage["permits_trusted_aggregate"] is False
    assert any(
        "have no open-interest row" in blocker for blocker in report.gex_blockers
    )


def test_the_tool_publishes_the_partition_beside_an_unchanged_report(
    retaining, tmp_path, capsys
):
    """The operator command gains a section and keeps its digest.

    ``report_hash`` covers exactly what it covered before, so a capture
    certified under an earlier release still reproduces its digest -- which is
    what makes the two committed live-capture fixtures still readable.
    """
    from src.tools.certify_thetadata_capture import main

    out = tmp_path / "report.json"
    main([str(retaining), "--json", str(out)])
    capsys.readouterr()
    payload = json.loads(out.read_text(encoding="utf-8"))

    assert payload["report_hash"] == certify_capture(retaining).report_hash()
    section = payload["analytical_universe"]
    assert section["analytical_universe_report_hash"] == (
        analytical_universe(retaining).report_hash()
    )
    assert (
        section["class_counts"][UniverseClass.EXCLUDED_EXPIRED_BEFORE_SESSION.value]
        == 8
    )


def test_the_partition_refuses_a_capture_that_does_not_certify(tmp_path):
    """A partition over unverified bytes would look exactly as authoritative."""
    with pytest.raises(AnalyticalUniverseError, match="does not certify"):
        analytical_universe(tmp_path / "nothing-here")
